---
title: "Course Schedule"
description: |
  The live video training session takes 5 hours and constists of five segments. Each segment contains a lecture, hands-on examples, exercises, and a Q&A session.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## <b style='color:gray;'>Segment 1</b><br><b style='font-size:20pt;'>The Grammar of Graphics</b>

*Duration: 60 min*

-  Motivation: The ggplot2 Showcase
-  Loading data into R
-  The Grammar of Graphics
-  Our First ggplot

→ Slides: [html](slides/01-grammar.html), [pdf](https://github.com/z3tt/hands-on-ggplot2/raw/main/slides/01-grammar.pdf)  
→ [Notebook](codes/01-grammar-rmarkdown.html)   
→ [Codes](codes/01-grammar-rmarkdown.Rmd)  

*Break: 5 min*

## <b style='color:gray;'>Segment 2</b><br><b style='font-size:20pt;'>Build Plots Layer by Layer</b>

*Duration: 60 min*

<p class="nospace"></p>
-  Create any Chart Type
-  Use Statistical Transformations
-  Plot Spatial Maps

→ Slides: [html](slides/02-layers.html), [pdf](https://github.com/z3tt/hands-on-ggplot2/raw/main/slides/02-layers.pdf)
→ [Notebook](codes/02-layers-rmarkdown.html)   
→ [Codes](codes/02-layers-rmarkdown.Rmd)  

*Break: 10 min*

## <b style='color:gray;'>Segment 3</b><br><b style='font-size:20pt;'>Polish Your Visualization</b>

*Duration: 60 min*

-  Work with Colors, Shapes, and Guides
-  Use Template Designs
-  Create Custom Themes

→ Slides: [html](slides/03-themes.html), [pdf](https://github.com/z3tt/hands-on-ggplot2/raw/main/slides/03-themes.pdf)
→ [Notebook](codes/03-themes-rmarkdown.html)   
→ [Codes](codes/03-themes-rmarkdown.Rmd)  

*Break: 5 min*

## <b style='color:gray;'>Segment 4</b><br><b style='font-size:20pt;'>Provide Context with Annotations</b>

*Duration: 45 min*

-  Insert Titles and Labels
-  Basic and Advanced Text Labeling
-  Add Images and Illustrations

→ Slides: [html](slides/04-annotation.html), [pdf](https://github.com/z3tt/hands-on-ggplot2/raw/main/slides/04-annotation.pdf)
→ [Notebook](codes/04-annotation-rmarkdown.html)   
→ [Codes](codes/04-annotation-rmarkdown.Rmd)  

*Break: 10 min*


## <b style='color:gray;'>Segment 5</b><br><b style='font-size:20pt;'>Create Multi–Panel Figures</b>

*Duration: 30 min*

-  Create Small Multiples (Facets)
-  Combine Multiple Plots with patchwork

→ Slides: [html](slides/05-multipanel.html), [pdf](https://github.com/z3tt/hands-on-ggplot2/raw/main/slides/05-multipanel.pdf)  
→ [Notebook](codes/05-multipanel-rmarkdown.html)   
→ [Codes](codes/05-multipanel-rmarkdown.Rmd)  


## <b style='color:gray;'>Wrap–Up</b><br><b style='font-size:20pt;'>Course Summary and Q&A</b>

*Duration: 15 min*


## Reuse {.appendix}

<i style=font-size:10pt;>Text and figures are licensed under Creative Commons Attribution <a href='https://creativecommons.org/licenses/by/4.0/'>CC BY 4.0</a>.<br>Note that figures in slides may be pulled in from external sources and may be licensed under different terms.</i>